export default {
  //   logo: require('../assets/images/logo.png'),
  selectedHome: require('../Assets/Images/selectedHomeIcn.png'),
  notifications: require('../Assets/Images/notifications.png'),
  ice: require('../Assets/Images/ice.png'),
  mega: require('../Assets/Images/mega.png'),
  mega2: require('../Assets/Images/mega2.png'),
  mega3: require('../Assets/Images/mega3.png'),

  percentage: require('../Assets/Images/percentage.png'),
  start: require('../Assets/Images/start.png'),
  gift: require('../Assets/Images/gift.png'),
  share: require('../Assets/Images/share.png'),
  stick: require('../Assets/Images/stick.png'),
  chocolate: require('../Assets/Images/choclate.png'),
  caramel: require('../Assets/Images/caramel.png'),
  vanilla: require('../Assets/Images/vannila.png'),
  add: require('../Assets/Images/add.png'),
  remove: require('../Assets/Images/remove.png'),
  next: require('../Assets/Images/next.png'),
  back: require('../Assets/Images/back.png'),
  pistachio: require('../Assets/Images/pistachio.png'),
  Hazelnut: require('../Assets/Images/Hazelnut.png'),
  wafer: require('../Assets/Images/wafer.png'),
  cartCar: require('../Assets/Images/cartCar.png'),
  chocklet: require('../Assets/Images/chocklet.png'),
  chocoMilk: require('../Assets/Images/chocoMilk.png'),
  topping1: require('../Assets/Images/toppingFirst.png'),
  topping2: require('../Assets/Images/toppingSecond.png'),
};
